### ISSUE TITLE
Errors while installing template

### ISSUE THREAD

**Issue by cehanshul** [Boanerges1996/admin-template-cra#1]
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: cra-template-boanergests@0.4.0
npm ERR! Found: react-scripts@5.0.1
npm ERR! node_modules/react-scripts
npm ERR!   dev react-scripts@"5.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react-scripts@"^4.0.0" from @craco/craco@6.4.5
npm ERR! node_modules/@craco/craco
npm ERR!   @craco/craco@"^6.4.5" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/anshul/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/anshul/.npm/_logs/2022-09-02T11_57_37_012Z-debug-0.log

**Comment by Boanerges1996** [comment]
Seen I guess is version issue
I have to allow legacy-peer-deps
